### ISSUE TITLE
inspect http request result

### ISSUE THREAD

**Issue by pablobcb** [facundoolano/restpect#2]
Id like to store and id coming from one request inside an atom to use it later in another test, is there a way i can inspect the request?

**Comment by facundoolano** [comment]
The request helpers (GET, POST, etc.) return the request response (as returned by clj-http), so you can extract whatever you need from that map before passing it to expect or another assertion function. Furthermore, assertion functions also return the response map, so you can do something like:

```clojure
(let [my-val (-> (POST url) created :body :id)
   ...)
```

To assert the status code is 201 and then extract :id from the response body.

**Comment by pablobcb** [comment]
thank you!
